flower:
	gcc flower.c -o flower
gardener:
	gcc gardener.c -o gardener
stopper:
	gcc ultimate_stopper.c -o stopper
all: flower gardener stopper
clean:
	rm -rf flower gardener stopper
remake:
	make clean all