flower:
	gcc flower.c -o flower -lrt
gardener:
	gcc gardener.c -o gardener -lrt
stopper:
	gcc ultimate_stopper.c -o stopper
all: flower gardener stopper
clean:
	rm -rf flower gardener stopper
remake:
	make clean all